In [1]:
#a+2b+3c+4d = 30
#f(x) = (a+2b+3c+4d) – 30

import numpy as np

# 2 Inisialisasi
n = 6

# 1 Pembentukan chromosome
chromosome = np.random.randint(0, 30,(n,4))
print("Chromosome : ", chromosome)

Chromosome :  [[19  3  8  2]
 [24 25  4 10]
 [ 8 22 11 28]
 [18 19  4  1]
 [20 17 12 16]
 [15 16 10 10]]


In [12]:
epoch = 0
while epoch < 200 :
    # 3 Evaluasi Chromosome
    fungsi_objektif = abs(chromosome[:,0] + 2*chromosome[:,1] + 3*chromosome[:,2] + 4*chromosome[:,3] - 30)
    print("------------ Epoch ke ",epoch + 1)
    print("Fungsi Objektif : ", fungsi_objektif)
    print("Rata-Rata Fungsi Objektif : ", np.average(fungsi_objektif))
    
    # 4 Seleksi Chromosome
    fitness = 1/(1 + fungsi_objektif)
    print("Fitness : ", fitness)
    
    total = fitness.sum()
    print("Total Fitness : ", total)
    
    P = fitness/total
    print("Probabilitas : ", P)
    
    C = np.cumsum(P)
    print("Nilai Kumulatif Probabilitas : ", C)
    
    acak = np.random.random((chromosome.shape[0]))
    print("R : ", acak)
    
    chromosome_2 = np.zeros((chromosome.shape[0],4))
    
    for i in range(acak.shape[0]):
        for j in range(chromosome.shape[0]):
            if acak[i] < C[j]:
                chromosome_2[i,:] = chromosome[j,:]
                break
                
    chromosome = chromosome_2
    print("Chromosone diPerbarui : ", chromosome)
    
    # 5 Crossover
    R = [np.random.random() for i in range(n)]
    print("Nlai Random : ", R)
    
    pc = 0.25
    
    flag = acak < pc
    print("Nilai Flag : ", flag)
    
    cross_chromosome = chromosome[[(i == True) for i in flag]]
    len_cross_chrom = len(cross_chromosome)
    
    cross_values = np.random.randint(1,3,len_cross_chrom)
    print("C : ", cross_values)
    
    copy_chromosome = np.zeros(cross_chromosome.shape)
    for i in range(cross_chromosome.shape[0]):
        copy_chromosome[i, :] = cross_chromosome[i, :]
        
    if len_cross_chrom == 1 :
        cross_chromosome = cross_chromosome
    else :
        for i in range(len_cross_chrom):
            c_val = cross_values[i]
            if i == len_cross_chrom - 1 :
                cross_chromosome[i, c_val:] = copy_chromosome[0, c_val:]
            else :
                cross_chromosome[i, c_val:] = copy_chromosome[i+1, c_val:]
                
    print("Crossover Chromosome : ",cross_chromosome)
    
    index_chromosome = 0
    index_chromosomebaru = 0
    for i in flag :
        if i == True :
            chromosome[index_chromosome, :] = cross_chromosome[index_chromosomebaru, :]
            index_chromosomebaru = index_chromosomebaru + 1
            index_chromosome = index_chromosome + 1
            
    print("Chromosome Baru : ", chromosome)
    
    # 6 Mutasi
    a, b = chromosome.shape[0], chromosome.shape[1]
    total_gen = a*b
    print("Total generasi : ", total_gen)
    
    pm = 0.1
    jumlah_mutasi = int(np.round(pm * total_gen))
    print("Jumlah Mutasi : ", jumlah_mutasi)
    
    gen_num = np.random.randint(0, total_gen - 1, jumlah_mutasi)
    print("Generate Angka Acak : ", gen_num)
    
    ganti_angka = np.random.randint(0,30, jumlah_mutasi)
    print("Nomor Yang Akan Diganti : ", ganti_angka)
    
    for i in range(jumlah_mutasi):
        a = gen_num[i]
        baris = a//4
        kolom = a%4
        chromosome[baris, kolom] = ganti_angka[i]
    
    print("Chromosome Mutasi : ", chromosome)
    
    epoch = epoch + 1
    print("-------------------------------") 

------------ Epoch ke  1
Fungsi Objektif :  [ 3.  1. 23.  1.  5.  1.]
Rata-Rata Fungsi Objektif :  5.666666666666667
Fitness :  [0.25       0.5        0.04166667 0.5        0.16666667 0.5       ]
Total Fitness :  1.9583333333333333
Probabilitas :  [0.12765957 0.25531915 0.0212766  0.25531915 0.08510638 0.25531915]
Nilai Kumulatif Probabilitas :  [0.12765957 0.38297872 0.40425532 0.65957447 0.74468085 1.        ]
R :  [0.42509368 0.9235021  0.15929903 0.27167122 0.59257433 0.26490258]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Nlai Random :  [0.7612768826087154, 0.6251005850038879, 0.6927725528571168, 0.5825154912699679, 0.4403914504782588, 0.15386077247113827]
Nilai Flag :  [False False  True False False False]
C :  [2]
Crossover Chromosome :  [[16.  3.  1.  1.]]
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  

Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [10 21]
Nomor Yang Akan Diganti :  [7 8]
Chromosome Mutasi :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  7.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  8.  1.  1.]]
-------------------------------
------------ Epoch ke  12
Fungsi Objektif :  [ 1.  1. 17.  1.  1.  9.]
Rata-Rata Fungsi Objektif :  5.0
Fitness :  [0.5        0.5        0.05555556 0.5        0.5        0.1       ]
Total Fitness :  2.1555555555555554
Probabilitas :  [0.23195876 0.23195876 0.0257732  0.23195876 0.23195876 0.04639175]
Nilai Kumulatif Probabilitas :  [0.23195876 0.46391753 0.48969072 0.72164948 0.95360825 1.        ]
R :  [0.06478442 0.58928975 0.33714527 0.98171288 0.07621676 0.25711038]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  8.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Nlai Random :  [0.6451785097572614, 0.5916548360072904, 0.10602895673758572, 0.41080454896749063, 0.424507463645

 [16.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [15  7]
Nomor Yang Akan Diganti :  [21  4]
Chromosome Mutasi :  [[16.  3.  4.  1.]
 [16.  3.  1.  4.]
 [16.  3.  1.  1.]
 [16.  3.  1. 21.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
-------------------------------
------------ Epoch ke  23
Fungsi Objektif :  [ 8. 11.  1. 79.  1.  1.]
Rata-Rata Fungsi Objektif :  16.833333333333332
Fitness :  [0.11111111 0.08333333 0.5        0.0125     0.5        0.5       ]
Total Fitness :  1.7069444444444444
Probabilitas :  [0.06509357 0.04882018 0.29292107 0.00732303 0.29292107 0.29292107]
Nilai Kumulatif Probabilitas :  [0.06509357 0.11391375 0.40683483 0.41415785 0.70707893 1.        ]
R :  [0.12494907 0.42678873 0.55399334 0.58491662 0.59155419 0.40450792]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Nlai Random :  [0.7549343889024505, 0.7598680064016384, 0.75517115168472, 0

 [16. 27.  1.  1.]]
-------------------------------
------------ Epoch ke  34
Fungsi Objektif :  [  1. 107.   1.   1.   1.  47.]
Rata-Rata Fungsi Objektif :  26.333333333333332
Fitness :  [0.5        0.00925926 0.5        0.5        0.5        0.02083333]
Total Fitness :  2.030092592592593
Probabilitas :  [0.24629418 0.004561   0.24629418 0.24629418 0.24629418 0.01026226]
Nilai Kumulatif Probabilitas :  [0.24629418 0.25085519 0.49714937 0.74344356 0.98973774 1.        ]
R :  [0.96369247 0.96035712 0.40125162 0.55573707 0.77444066 0.98539148]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Nlai Random :  [0.5758555621088952, 0.8268844508645987, 0.6668008477580345, 0.26072536925878675, 0.40255829521648867, 0.9701282324260674]
Nilai Flag :  [False False False False False False]
C :  []
Crossover Chromosome :  []
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  

-------------------------------
------------ Epoch ke  45
Fungsi Objektif :  [ 1.  1.  3.  1. 74.  1.]
Rata-Rata Fungsi Objektif :  13.5
Fitness :  [0.5        0.5        0.25       0.5        0.01333333 0.5       ]
Total Fitness :  2.2633333333333336
Probabilitas :  [0.22091311 0.22091311 0.11045655 0.22091311 0.00589102 0.22091311]
Nilai Kumulatif Probabilitas :  [0.22091311 0.44182622 0.55228277 0.77319588 0.77908689 1.        ]
R :  [0.04905638 0.04410428 0.66028949 0.17538146 0.11549025 0.53103691]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [20.  3.  1.  1.]]
Nlai Random :  [0.2356767301036743, 0.026706750935444834, 0.608763626901476, 0.3342626013705673, 0.4345651114777429, 0.748972188774359]
Nilai Flag :  [ True  True False  True  True False]
C :  [2 1 2 1]
Crossover Chromosome :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.

 [16.  3.  1.  1.]]
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [12 15]
Nomor Yang Akan Diganti :  [1 9]
Chromosome Mutasi :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [ 1.  3.  1.  9.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
-------------------------------
------------ Epoch ke  56
Fungsi Objektif :  [ 1.  1.  1. 16.  1.  1.]
Rata-Rata Fungsi Objektif :  3.5
Fitness :  [0.5        0.5        0.5        0.05882353 0.5        0.5       ]
Total Fitness :  2.5588235294117645
Probabilitas :  [0.1954023  0.1954023  0.1954023  0.02298851 0.1954023  0.1954023 ]
Nilai Kumulatif Probabilitas :  [0.1954023 0.3908046 0.5862069 0.6091954 0.8045977 1.       ]
R :  [0.75939557 0.91922607 0.54999517 0.32932458 0.57365749 0.90075157]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [1

Fitness :  [0.5        0.05882353 0.5        0.5        0.02564103 0.5       ]
Total Fitness :  2.08446455505279
Probabilitas :  [0.23986975 0.02821997 0.23986975 0.23986975 0.01230101 0.23986975]
Nilai Kumulatif Probabilitas :  [0.23986975 0.26808973 0.50795948 0.74782923 0.76013025 1.        ]
R :  [0.56417445 0.53247852 0.82733098 0.04669503 0.47770554 0.26138923]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [ 1.  3.  1.  1.]]
Nlai Random :  [0.12330916684991733, 0.23521134575960878, 0.7007267992972059, 0.5153940447285537, 0.7842514347020051, 0.1267568804347613]
Nilai Flag :  [False False False  True False False]
C :  [1]
Crossover Chromosome :  [[16.  3.  1.  1.]]
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [ 1.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [ 8 19]
Nomor Yang Akan Diganti :  [16  2]
Chromos

R :  [0.07048924 0.26771008 0.21139994 0.60123961 0.35331695 0.39644416]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Nlai Random :  [0.9048953953487471, 0.5499895923351678, 0.3730689149013249, 0.1615498980431872, 0.7676731863442081, 0.2693869950961483]
Nilai Flag :  [ True False  True False False False]
C :  [2 2]
Crossover Chromosome :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [13 10]
Nomor Yang Akan Diganti :  [25 16]
Chromosome Mutasi :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3. 16.  1.]
 [16. 25.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
-------------------------------
------------ Epoch ke  77
Fungsi Objektif :  [ 1.  1. 44. 43.  1.  1.]
Rata-Rata Fungsi Objektif :  15.16666666666666

 [16.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [7 4]
Nomor Yang Akan Diganti :  [10 25]
Chromosome Mutasi :  [[16.  3.  1.  1.]
 [25.  3.  1. 10.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
-------------------------------
------------ Epoch ke  87
Fungsi Objektif :  [ 1. 44.  1.  1.  1.  1.]
Rata-Rata Fungsi Objektif :  8.166666666666666
Fitness :  [0.5        0.02222222 0.5        0.5        0.5        0.5       ]
Total Fitness :  2.522222222222222
Probabilitas :  [0.19823789 0.00881057 0.19823789 0.19823789 0.19823789 0.19823789]
Nilai Kumulatif Probabilitas :  [0.19823789 0.20704846 0.40528634 0.60352423 0.80176211 1.        ]
R :  [0.99421995 0.60521159 0.23485424 0.94308677 0.48960248 0.51074197]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Nlai Random :  [0.9934007719250522, 0.8589330566056135, 0.1637340328967103, 0.7

Fitness :  [0.5        0.5        0.5        0.16666667 0.02       0.33333333]
Total Fitness :  2.02
Probabilitas :  [0.24752475 0.24752475 0.24752475 0.08250825 0.00990099 0.1650165 ]
Nilai Kumulatif Probabilitas :  [0.24752475 0.4950495  0.74257426 0.82508251 0.8349835  1.        ]
R :  [0.07048847 0.93507672 0.21071458 0.88742172 0.51554379 0.14062087]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  2.  1.]
 [16.  3.  1.  1.]
 [16.  3.  2.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Nlai Random :  [0.555619873916951, 0.569460486727245, 0.7376136660061229, 0.2827412229044388, 0.6530416481823986, 0.23962195567104894]
Nilai Flag :  [ True False  True False False  True]
C :  [1 1 2]
Crossover Chromosome :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  2.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [ 8 15]
Nomor Yang Akan

Nilai Kumulatif Probabilitas :  [0.2244389  0.44887781 0.67331671 0.68578554 0.91022444 1.        ]
R :  [0.32053052 0.16090701 0.83465374 0.16653388 0.50161496 0.18156916]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Nlai Random :  [0.6072330635718309, 0.20828501644301733, 0.24387415490098152, 0.6377808167358554, 0.8324767748766114, 0.41269872540929486]
Nilai Flag :  [False  True False  True False  True]
C :  [1 1 2]
Crossover Chromosome :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [17 17]
Nomor Yang Akan Diganti :  [ 2 11]
Chromosome Mutasi :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16. 11.  1.  1.]
 [16.  3.  1.  1.]]
-------------------------

Probabilitas :  [0.23659306 0.00630915 0.23659306 0.23659306 0.23659306 0.04731861]
Nilai Kumulatif Probabilitas :  [0.23659306 0.24290221 0.47949527 0.71608833 0.95268139 1.        ]
R :  [0.14969922 0.07147634 0.20582525 0.33860208 0.36652811 0.81048697]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Nlai Random :  [0.2162804723691465, 0.2583887314991091, 0.5647449582080581, 0.34657528886255085, 0.8969734691815444, 0.13009539352660082]
Nilai Flag :  [ True  True  True False False False]
C :  [2 2 1]
Crossover Chromosome :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [21  0]
Nomor Yang Akan Diganti :  [19 21]
Chromosome Mutasi :  [[21.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]


 [16.  3.  1.  1.]]
Nlai Random :  [0.8913512443191862, 0.8156072723257559, 0.04700510735956387, 0.27598648823432237, 0.5659205313784206, 0.7507654549510259]
Nilai Flag :  [False False False False  True False]
C :  [2]
Crossover Chromosome :  [[16.  3.  1.  1.]]
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [10  4]
Nomor Yang Akan Diganti :  [13 11]
Chromosome Mutasi :  [[16.  3.  1.  1.]
 [11.  3.  1.  1.]
 [16.  3. 13.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
-------------------------------
------------ Epoch ke  130
Fungsi Objektif :  [ 1.  6. 35.  1.  1.  1.]
Rata-Rata Fungsi Objektif :  7.5
Fitness :  [0.5        0.14285714 0.02777778 0.5        0.5        0.5       ]
Total Fitness :  2.1706349206349205
Probabilitas :  [0.23034735 0.06581353 0.01279707 0.23034735 0.23034735 0.23034735]
Nilai Kumulatif Probabili

Fungsi Objektif :  [ 1.  1. 19. 15.  1.  1.]
Rata-Rata Fungsi Objektif :  6.333333333333333
Fitness :  [0.5    0.5    0.05   0.0625 0.5    0.5   ]
Total Fitness :  2.1125
Probabilitas :  [0.23668639 0.23668639 0.02366864 0.0295858  0.23668639 0.23668639]
Nilai Kumulatif Probabilitas :  [0.23668639 0.47337278 0.49704142 0.52662722 0.76331361 1.        ]
R :  [0.88556417 0.78409486 0.35976996 0.72700467 0.59456028 0.10359413]
Chromosone diPerbarui :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Nlai Random :  [0.5990973993009477, 0.15996519204334425, 0.6116425681430704, 0.21557153118861438, 0.47963764062375513, 0.6299496026905295]
Nilai Flag :  [False False False False False  True]
C :  [2]
Crossover Chromosome :  [[16.  3.  1.  1.]]
Chromosome Baru :  [[16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka

 [13.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [ 1 21]
Nomor Yang Akan Diganti :  [23 29]
Chromosome Mutasi :  [[16. 23.  1.  1.]
 [16.  3.  1.  1.]
 [13.  3.  1.  1.]
 [ 6.  8.  1.  1.]
 [13.  3.  1.  1.]
 [13. 29.  1.  1.]]
-------------------------------
------------ Epoch ke  150
Fungsi Objektif :  [39.  1.  4.  1.  4. 48.]
Rata-Rata Fungsi Objektif :  16.166666666666668
Fitness :  [0.025      0.5        0.2        0.5        0.2        0.02040816]
Total Fitness :  1.4454081632653062
Probabilitas :  [0.01729615 0.34592305 0.13836922 0.34592305 0.13836922 0.01411931]
Nilai Kumulatif Probabilitas :  [0.01729615 0.3632192  0.50158842 0.84751147 0.98588069 1.        ]
R :  [0.80896111 0.29647999 0.11992955 0.30643852 0.13684455 0.45340632]
Chromosone diPerbarui :  [[ 6.  8.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [16.  3.  1.  1.]
 [13.  3.  1.  1.]]
Nlai Random :  [0.179648768667941, 0.7285301911561277, 0.05320069748511935

 [17.  3.  1.  1.]]
Nlai Random :  [0.42245663700921143, 0.7904201817492421, 0.5035387215739958, 0.6458487870887548, 0.0860565261356322, 0.5515789449617676]
Nilai Flag :  [ True False False False False False]
C :  [1]
Crossover Chromosome :  [[17.  3.  1.  1.]]
Chromosome Baru :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [10 22]
Nomor Yang Akan Diganti :  [11 25]
Chromosome Mutasi :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3. 11.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3. 25.  1.]]
-------------------------------
------------ Epoch ke  160
Fungsi Objektif :  [ 0.  0. 30.  0.  0. 72.]
Rata-Rata Fungsi Objektif :  17.0
Fitness :  [1.         1.         0.03225806 1.         1.         0.01369863]
Total Fitness :  4.045956694653115
Probabilitas :  [0.24716033 0.24716033 0.00797291 0.24716033 0.24716033 0.00338576]
Nilai Kumulatif Probabilit

Probabilitas :  [0.24154589 0.24154589 0.00966184 0.24154589 0.24154589 0.02415459]
Nilai Kumulatif Probabilitas :  [0.24154589 0.48309179 0.49275362 0.73429952 0.97584541 1.        ]
R :  [0.3177946  0.62600969 0.30381275 0.31485776 0.53976177 0.91287851]
Chromosone diPerbarui :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]]
Nlai Random :  [0.2813174605351896, 0.3168913809761079, 0.1580364037974804, 0.06870344746073165, 0.5365657733900607, 0.4373260919871548]
Nilai Flag :  [False False False False False False]
C :  []
Crossover Chromosome :  []
Chromosome Baru :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [20 17]
Nomor Yang Akan Diganti :  [14 19]
Chromosome Mutasi :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17. 19.  1.  1.]
 [14.  3.  1.  1.]]
---

Fitness :  [0.02325581 1.         1.         1.         1.         0.33333333]
Total Fitness :  4.3565891472868215
Probabilitas :  [0.00533808 0.22953737 0.22953737 0.22953737 0.22953737 0.07651246]
Nilai Kumulatif Probabilitas :  [0.00533808 0.23487544 0.46441281 0.69395018 0.92348754 1.        ]
R :  [0.81044466 0.29117363 0.18693414 0.47035303 0.65067059 0.69018051]
Chromosone diPerbarui :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]]
Nlai Random :  [0.24864997406452582, 0.6684186889558038, 0.8178078692301909, 0.08832871463616021, 0.30300522256270135, 0.5667564276464075]
Nilai Flag :  [False False  True False False False]
C :  [1]
Crossover Chromosome :  [[17.  3.  1.  1.]]
Chromosome Baru :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [21  8]
Nomor Yang Akan Diganti :  [15  2]
Chro

Nilai Kumulatif Probabilitas :  [0.00306279 0.07427259 0.35911179 0.43032159 0.7151608  1.        ]
R :  [0.62112605 0.29078191 0.25876278 0.31032923 0.96218107 0.89657413]
Chromosone diPerbarui :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]]
Nlai Random :  [0.8355348973182637, 0.4762975055820706, 0.4377212257343971, 0.8002424863530183, 0.8970053855327167, 0.7350267354120866]
Nilai Flag :  [False False False False False False]
C :  []
Crossover Chromosome :  []
Chromosome Baru :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [12 13]
Nomor Yang Akan Diganti :  [10  4]
Chromosome Mutasi :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [10.  4.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]]
-------------------------------
------------ Epoch ke  191
Fungsi Objektif :  [0. 0. 0. 

Probabilitas :  [0.23480663 0.23480663 0.01381215 0.23480663 0.23480663 0.04696133]
Nilai Kumulatif Probabilitas :  [0.23480663 0.46961326 0.48342541 0.71823204 0.95303867 1.        ]
R :  [0.80199464 0.35228444 0.87644825 0.61118105 0.10494781 0.93412672]
Chromosone diPerbarui :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]]
Nlai Random :  [0.9197032991182279, 0.5839330422326348, 0.41266203902908694, 0.30811473244403587, 0.186123705979528, 0.3649717463713287]
Nilai Flag :  [False False False False  True False]
C :  [1]
Crossover Chromosome :  [[17.  3.  1.  1.]]
Chromosome Baru :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1.  1.]]
Total generasi :  24
Jumlah Mutasi :  2
Generate Angka Acak :  [19 11]
Nomor Yang Akan Diganti :  [ 4 12]
Chromosome Mutasi :  [[17.  3.  1.  1.]
 [17.  3.  1.  1.]
 [17.  3.  1. 12.]
 [17.  3.  1.  1.]
 [17.  3.  1.  4.]
 [17.